---

- name: Copy binary
  copy:
    src: "{{CUSPCLI_BINARY}}"
    dest: /usr/bin/cuspcli
    mode: 0755
  notify: restart cuspcli

- name: Copy service
  template:
    src: cuspcli.service.j2
    dest: /etc/systemd/system/cuspcli.service
  notify: systemctl

